title: Causal effects of policy interventions
logo: /img/workshop_logo.svg
description: Materials for a workshop on causal effects of policy interventions.
theme: jekyll-theme-minimal
github:
    is_project_page: false
